---
#title: "About"
#author: "Mychala Walker"
#date: "8/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### About
Mychala Walker is a Virginia State University Presidential Scholar, Andrew Young Student Leader, and Thurgood Marshall College Fund scholar. During her time at Virginia State, she has studied Political Science and gained numerous accolades including Outstanding Freshman of the Year, Outstanding Sophomore of the Year, and the Rosa Parks Award for Academic Excellence. You can learn more of these accomplishments in the Resume tab. 
<br>
<br>
Mychala has worked on both solo and team research projects. Her research is driven by both her love for politics and her passion for social justice and public health. She has presented projects at the Virginias Collegiate Honors Council Conference and UVA’s Biocomplexity Institute DSPG Symposium. She has also worked with a number of political organizations and interned for State Senator Jeremy McPike. While working with the Data Science for the Public Good Program, she has learned data science and coding techniques and enhance her research abilities. You can learn more about these projects on the Projects tab.
