---
title: "X-Culture"
description: ""
author: "Mychala Walker"
date: "8/28/2020"
output: html_document
tags: []
weight: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#### <b> Title: <br>
#### X-Culture <br>

<br>

#### <b> Date: <br>
#### 4-23-2020 <br>

<br>

#### <b> Author(s): <br>
#### Arianna Bonacina, Claudio Luis De Melo Pereira, Austin Roberts, Juan Sebastian Casas Orjuela, Mychala Walker <br>

<br>

#### <b> About X - Culture: <br>
X-Culture is an international business collaboration and consulting project. Thousands of students from around the world work in teams to solve challenges from real international businesses. <br>
ZENCV is an online platform for professional resume design & writing services that will match customers with
freelancers like top-notch CV designers and HR/industry experts to create high-quality, custom-made CVs. <br>
The goal of this project was to aid ZenCV in their market expansion strategy. In our approach we completed market research, competition analysis, and product development, among other tasks. <br>
Our team was selected to be the recipients of the 2020-1 X-Culture Best Team Award.<br>
The link to our project write-up is [here](/pdf/63.pdf).

